spring.application.name=liste-noel

# --- Datasource ---
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://postgresql-tenalic.alwaysdata.net:5432/tenalic_pairing_site
spring.datasource.username=${userBdd}
spring.datasource.password=${passwordBdd}
spring.datasource.hikari.schema=${schemaBdd}


spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- Hibernate SQL logs ---
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# --- External services ---
mock=${mock}
private_secret_token=${private_secret_token}
salt=${salt}
base_url=${base_url}

# --- Email ---
usernameEmail=${username_email}
password_email=${password_email}
host_email=${host_email}

# --- Logging ---
logging.level.root=INFO
logging.level.org.postgresql=WARN
logging.level.com.zaxxer.hikari=INFO
logging.level.com.zaxxer.hikari.HikariConfig=INFO
logging.level.com.zaxxer.hikari.HikariDataSource=WARN
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=WARN
logging.level.org.springframework.orm.jpa=WARN
logging.level.org.springframework.transaction=DEBUG
logging.level.org.springframework.boot.web=DEBUG

# --- HikariCP tuning ---
spring.datasource.hikari.initialization-fail-timeout=10000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.maximum-pool-size=5

spring.messages.basename=messages
spring.messages.encoding=UTF-8

jwt.secret=cb0d291c838d3e1b13013c126f330959748e7ea2138d3bdde27c04b8fc150115
jwt.expiration=86400